### ISSUE TITLE
Surface Check

### ISSUE THREAD

**Issue by annick-tanguay** [Deep-MI/hipsta#5]
Thank you for making this available to all! I'm so excited to try it out.

I obtained segmentation from Freesurfer 7.4.1, doing recon-all and subsequently using the  hippocampal pipeline with a T2w scan of the hippocampus as an additional scan. I tested your pipeline with a local installation and also a docker version because I wasn't sure where things got stuck. I'm on Ubuntu 22.04.4 and installed everything today.

Locally, I did 

`run_hipsta --filename lh.hippoAmygLabels-T1-UseT1.v22.mgz --hemi lh --lut freesurfer --outputdir /home/dufflab/Documents/DuffLab_MRI/hipsta_test/output --remesh`

On a side note, I tried the CA, HBT, and FS60 versions of the segmentation, and that didn't work. Trial/error! But the above got me further.

I get the error 

> [INFO: check_surface.py] Euler number for /output/lh.surf.vtk is -36457
> [INFO: check_surface.py] Surface contains holes. Please edit the corresponding hippocampal segmentation and re-run.
> [INFO: hipsta.py] Hipsta finished WITH ERRORS.
> [ERROR: hipsta.py] Error Information:
> [ERROR: hipsta.py] Type: <class 'AssertionError'>
> [ERROR: hipsta.py] Value: ('Check surface failed (stage: surface)',)

I tried to change --mca, did --smooth 6 (not sure what is appropriate), --long-filter --remesh (as you see above). Nothing quite helped. The only thing I can do to move things along is --no-check-surface --no-check-boundaries but that ultimately fails. 
I am not seeing major issues in the segmentation or the mesh. Here's the QC 
![lh mesh](https://github.com/Deep-MI/hipsta/assets/167731729/ac5aaf67-d586-4d59-b413-bb92210cb33b)

I also tried an ASHS ABC that I thought had done a decent job, but it turns out the mesh did have a huge hole, so I get the complaint there. 

Do you have any ideas for me on what to do to be able to proceed? Ideally I would love to find a way to fix automatically the meshes because editing the Freesurfer segmentation is not easy and in the case above, the issue is not clear to me. If manual editing of the segmentation is the only way to go, it would be great to have a way to flag the problematic slice/area. It would simplify editing so much. I tried 2-3 participants so far, so I don't think it's just one bad case.

**Comment by kdiers** [comment]
Hi, thanks for your comments and for sharing your observations. The creation of meshes/surfaces from segmentations can indeed be tricky, and how well it works may to a certain extend depend on the dataset characteristics. The challenge is to find parameters that result in neither too much nor too little preprocessing for a given dataset. It is always a bit difficult to give recommendations without looking at the data, but personally I think using the `--long-filter` flag makes sense, and it may also be useful to gradually increase the size of this filter using the `--long-filter-size` argument, starting with 1. Similarly, I would try increasing the `--gauss-filter-size` step by step (i.e., `--gauss-filter-size 1 50`, `--gauss-filter-size 2 50`, etc.). Beyond that, one would probably need to look at the intermediate images/surfaces to be able to give more specific suggestions. Hope this helps!
